---
# Configuration for fetching the Argo CD notifications
externalSecret:
  # The name of the secret in the secrets manager that contains OAuth token for Slack.
  # The should be within the path /CLUSTER_NAME/global/SECRET_NAME
  secretName: dev/global/notifications
