---
name: Validation

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  validate-promotion:
    name: Validate Promotion
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'promotion/skip-validation') }}
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Validate Promotion
        uses: appvia/appvia-cicd-workflows/.github/actions/kubernetes-platform-promotion@main
        with:
          cicd-branch: main
          cicd-repository: appvia/appvia-cicd-workflows
          github-token: ${{ secrets.GITHUB_TOKEN }}
          promotion-order: dev,qa,uat,staging,prod
          workloads-dir: workloads/applications

  validate-yaml:
    name: Validate YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pip install yamllint
      - run: make lint-yaml

  validate-commitlint:
    name: Validate Commitlint
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: npm install @commitlint/config-conventional @commitlint/cli
      - name: Run Commitlint
        id: commitlint
        run: git log --pretty=format:"%s" origin/${{ github.event.pull_request.base.ref }}..HEAD | npx commitlint --from=origin/${{ github.event.pull_request.base.ref }}

  validate-terraform-lint:
    name: Lint Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: terraform-linters/setup-tflint@v6
        name: Setup TFLint
        with:
          tflint_version: v0.61.0
          cache: true
      - run: make lint-terraform

  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.0
      - run: make validate-terraform

  validate-scripts:
    name: Validate Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          path: scripts

  validate-schema:
    name: Validate Schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: appvia/kubernetes-platform/.github/actions/validate-schemas@main
        with:
          clusters: clusters
          workloads: workloads
