---
name: Validation

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-yaml:
    name: Validate YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install yamllint
      - run: make lint-yaml

  validate-commitlint:
    name: Validate Kustomize
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install @commitlint/config-conventional @commitlint/cli
      - name: Run Commitlint
        id: commitlint
        run: npx commitlint --config commitlint.config.js --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}

  validate-terraform-lint:
    name: Lint Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v6
        name: Setup TFLint
        with:
          tflint_version: v0.61.0
          cache: true
      - run: make lint-terraform

  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.14.0
      - run: make validate-terraform

  validate-scripts:
    name: Validate Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          path: scripts

  validate-schema:
    name: Validate Schema
    runs-on: ubuntu-latest
    steps:
      - uses: appvia/kubernetes-platform/.github/actions/validate-schemas@main
        with:
          clusters: clusters
          workloads: workloads
